# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  pipelines:
    - pipeline: releasepipeline
      source: slackbotazfunction
      trigger:
        branches:
          - main

jobs:
- deployment: DeployDev
  displayName: Deploy to Dev
  environment: dev
  pool:
    vmImage: ubuntu-latest
  strategy:
    runOnce:
      deploy:
        steps:
          - script: |  
              echo 'Hello world from Dev!'
- deployment: DeployAcc
  displayName: Deploy to acc
  environment: acc
  pool:
    vmImage: ubuntu-latest
  strategy:
    runOnce:
      deploy:
        steps:
          - script: |  
              echo 'Hello world from Acc!'
- deployment: DeployPrd
  displayName: Deploy to Prd
  environment: prd
  pool:
    vmImage: ubuntu-latest
  strategy:
    runOnce:
      deploy:
        steps:
          - script: |  
              echo 'Hello world from Prd!'